### ISSUE TITLE
用户词典迁移部分说明存在偏误

### ISSUE THREAD

**Issue by H-Tung** [Mintimate/DocVitePressOMR#5]
我在按照 [官网用户迁移说明](https://www.mintimate.cc/zh/guide/deviceSync.html#用户词典迁移) 部分迁移时反复失败，后参考雾凇拼音的文档与 issue 迁移成功，发现文档存在以下问题：

1. 简繁转换的“服务”是 MacOS 的功能而不是某个软件 （参考 https://github.com/iDvel/rime-ice/issues/108#issuecomment-1477356377 中提到 Sublime Text 同样拥有此功能）
2. 旧词典的命名应当与目前使用的词典名一致（例如 `rime_mint.userdb.txt` ），并且放在另建的新文件夹 `sync_dir/temp` 或类似地方。其原理是 rime 同步时将各个设备上的字典合并，如果是 `custom_dict.userdb.txt` 这样的命名、或者放在了同步目录的根目录下是不会合并到目前使用的词典中的

参考资料：
1. https://github.com/iDvel/rime-ice/issues/108
2.  [雾凇拼音#用户词典迁移](https://dvel.me/posts/rime-ice/#用户词典迁移)

**Comment by Mintimate** [comment]
没懂，issue里的不是最后发现是软件替换时候Tab变空格么？ 按道理同步是不需要手动创建一个temp目录让引擎进行合并的呀。

还有就是你指的简体转换服务是macOS的功能不是软件？ 指OpenCC么？ 这个macOS自己是没有自带的，如果你要使用，可以用软件包管理器brew先安装：

```bash
brew install opencc
```

Linux可以用apt安装，包名也是OpenCC。

**Comment by H-Tung** [comment]
# 词典位置与命名
> 没懂，issue里的不是最后发现是软件替换时候Tab变空格么？ 按道理同步是不需要手动创建一个temp目录让引擎进行合并的呀。

同步的逻辑应该是以下情况：
|新词库|旧词库|是否能够合并|
|:---|:---|:---:|
|`syncdir\A\A.userdb.txt`|`syncdir\B\A.userdb.txt`|☑|
|`syncdir\A\A.userdb.txt`|`syncdir\A.userdb.txt`  |❎|
|`syncdir\A\A.userdb.txt`|`syncdir\B\B.userdb.txt`|❎|
|`syncdir\A\A.userdb.txt`|`syncdir\A\B.userdb.txt`|❎|

所以要迁移旧有的 `luna.userdb.txt` 到 `rime_mint.userdb.txt` 中，应该在 `syncdir` 下新建一个文件夹，并把 `luna.userdb.txt` 更名为`rime_mint.userdb.txt` 。这样合并时 Rime 会认为这是另一个设备上的词库将其合并过来，否则不同词库间不会合并。

# MacOS 简繁转换
> 还有就是你指的简体转换服务是macOS的功能不是软件？ 指OpenCC么？ 这个macOS自己是没有自带的，如果你要使用，可以用软件包管理器brew先安装：

我指的是帮助文档中的这段表述：
>简单的方法，比如通过VSCode打开➡️全选➡️**左上角Code➡️服务➡️将文本转换为简体中文。**

这是 MacOS 的系统服务，参见 [在 Mac 上转换中文或拉丁字符 - 官方 Apple 支持 (中国)](https://support.apple.com/zh-cn/guide/chinese-input-method/mchlp2865/104/mac/14.0)。
雾凇拼音的文档中明确指出是 MacOS 上的 VSCode（虽然任意编辑器都可以），但是薄荷的文档中删除了 MacOS 容易让人误会这是 VSCode 的功能。

**Comment by Mintimate** [comment]
哦哦，这下懂了。VSCode那个我到时候改一下。 

同步的逻辑，用目前文档上的那种可以么？ 就是先重命名为目标输入法词典，再把内部`#@/db_name`替换为目标输入法词典呢？
